# Save as: confs/ghop_stage2_temporal_only.yaml

# ================================================================
# STAGE 2: Temporal Consistency + GHOP SDS
# Based on successful Stage 1 (100-epoch) checkpoint
# ================================================================

# Phase Configuration
phase3:
  enabled: true
  ghop:
    config_path: checkpoints/ghop/config.yaml
    device: cuda
    text_lib: null
    unet_checkpoint: checkpoints/ghop/last.ckpt
    unet_use_pretrained: true
    unified_checkpoint: checkpoints/ghop/last.ckpt
    vqvae_checkpoint: checkpoints/ghop/last.ckpt
    vqvae_use_pretrained: true
  grid_resolution: 24
  phase3_end_iter: 99999
  phase3_start_iter: 0
  sds:
    diffusion_steps: 1000
    guidance_scale: 4.0
    max_step_ratio: 0.98
    min_step_ratio: 0.02
    noise_schedule: linear
    prediction_respacing: 50
  sds_iters: 1
  spatial_lim: 1.5
  use_modular_init: true
  w_sds: 100.0            # Start conservative, can increase
  warmup_iters: 0

phase4:
  enabled: false          # Disable for Stage 2

phase5:
  enabled: false          # Disable for Stage 2

# Dataset Configuration
dataset:
  train:
    type: "train"
    batch_size: 1         # Keep small for GHOP SDS
    drop_last: false
    shuffle: true
    num_workers: 4
    prefetch_factor: 2

  valid:
    type: "val"
    enabled: false        # Disable validation for faster training
    batch_size: 1

# Training Configuration
training:
  num_epochs: 30
  max_steps: -1
  eval_every_epoch: 999   # Skip evaluation during Stage 2
  log_every: 10
  gradient_clip: 1.0      # Increase for GHOP SDS stability

# Loss Configuration
loss:
  w_rgb: 1.0              # Keep RGB loss
  w_mask: 0.1
  w_eikonal: 1.0
  w_smooth: 0.005
  w_temporal: 1.0         # Temporal consistency
  rgb_loss_type: "l1"

# ================================================================
# MODEL: MUST MATCH STAGE 1 ARCHITECTURE EXACTLY
# ================================================================
model:
  implicit_network:
    feature_vector_size: 256    # ✅ Match Stage 1
    d_in: 3
    d_out: 1
    dims: [256, 256, 256, 256]  # ✅ Match Stage 1
    init: geometry
    bias: 0.6
    skip_in: [4]                # ✅ Match Stage 1
    weight_norm: true
    multires: 6                 # ✅ Match Stage 1
    cond: pose

  rendering_network:
    feature_vector_size: 256    # ✅ Match Stage 1
    mode: pose
    d_in: 270                   # ✅ Match Stage 1
    d_out: 3
    dims: [256, 256, 256, 256, 256, 256, 256, 256]  # ✅ Match Stage 1
    weight_norm: true
    multires_view: 0            # ✅ Match Stage 1
    time_code_dim: 32
    d_implicit_features: 256

  bg_implicit_network:
    feature_vector_size: 256    # ✅ Match Stage 1
    d_in: 4
    d_out: 1
    dims: [256, 256, 256]       # ✅ Match Stage 1
    init: none
    bias: 0.0
    skip_in: []
    weight_norm: true
    multires: 10                # ✅ Match Stage 1
    cond: frame
    dim_frame_encoding: 32

  bg_rendering_network:
    feature_vector_size: 256    # ✅ Match Stage 1
    mode: nerf_frame_encoding
    d_in: 259                   # ✅ Match Stage 1
    d_out: 3
    dims: [128]                 # ✅ Match Stage 1
    weight_norm: true
    multires_view: 4            # ✅ Match Stage 1
    dim_frame_encoding: 32

  density:
    params_init:
      beta: 0.1
    beta_min: 0.0001

  ray_sampler:
    near: 0.0
    N_samples: 64               # ✅ Match Stage 1
    N_samples_eval: 128         # ✅ Match Stage 1
    N_samples_extra: 32         # ✅ Match Stage 1
    eps: 0.1
    beta_iters: 10
    max_total_iters: 5
    N_samples_inverse_sphere: 32

  sdf_bounding_sphere: 1.5      # ✅ Match Stage 1

# Optimizer Configuration
optimizer:
  lr: 0.00005                   # Lower LR for fine-tuning
  type: "adam"
  weight_decay: 0.0

experiment:
  name: 'ghop_stage2_temporal'
