# File: confs/test_checkpoint_loading.yaml
# Update checkpoint path to use ../checkpoints (relative to code/)

defaults:
  - sanity_check_fast

# ================================================================
# PHASE 3: Add phase3_start_iter
# ================================================================
phase3:
  enabled: false
  use_modular_init: true

  ghop:
    unified_checkpoint: "checkpoints/ghop/last.ckpt"
    vqvae_checkpoint: "checkpoints/ghop/last.ckpt"
    unet_checkpoint: "checkpoints/ghop/last.ckpt"
    config_path: "checkpoints/ghop/config.yaml"
    vqvae_use_pretrained: true
    unet_use_pretrained: true
    device: "cuda"
    text_lib: null

  # ================================================================
  # FIX 1: Add phase3_start_iter
  # ================================================================
  phase3_start_iter: 0            # ← ADD: Phase 3 starts at iteration 0
  warmup_iters: 0
  w_sds: 5000.0
  sds_iters: 1
  grid_resolution: 32
  spatial_lim: 1.5

  sds:
    diffusion_steps: 1000
    prediction_respacing: 10
    noise_schedule: "linear"
    min_step_ratio: 0.02
    max_step_ratio: 0.98
    guidance_scale: 4.0

# ========================================================================
# PHASE 4: CONTACT REFINEMENT (NEW - Optimized for 2-minute runs)
# ========================================================================
phase4:
  # Master switch
  enabled: true

  # ======================================================================
  # FAST TEST SCHEDULE: Total 30 iterations (20 SDS + 10 Contact)
  # ======================================================================
  contact_start_iter: 20          # Start RIGHT after Phase 3 ends
  contact_duration: 10            # Only 10 iterations for testing
  contact_warmup_iters: 5         # Fast warmup (5 iterations)

  # ======================================================================
  # Contact Refinement Module (NESTED - matches code expectations)
  # ======================================================================
  contact_refinement:
    enabled: true

    # Thresholds (keep reasonable values)
    contact_thresh: 0.01            # 10mm contact zone
    collision_thresh: 0.005         # 5mm penetration threshold

    # Loss weights (moderate values for testing)
    w_penetration: 50.0             # REDUCED from 100.0 for stability
    w_attraction: 5.0               # REDUCED from 10.0 for stability
    w_damping: 0.0                  # Disabled for speed

    # Contact zones
    contact_zones: "zones"          # Fixed fingertips (fastest)

  # ======================================================================
  # Mesh Extraction (NESTED - matches code expectations)
  # ======================================================================
  mesh_extraction:
    enabled: true

    # CRITICAL: Low resolution for speed
    resolution: 64                  # REDUCED from 128 for 2x speedup
    threshold: 0.0
    extract_every: 1                # Extract every iteration

  # ======================================================================
  # Master Contact Weight
  # ======================================================================
  w_contact: 10.0                   # Master multiplier

  # ======================================================================
  # Logging (Minimal for speed)
  # ======================================================================
  log_contact_every: 5              # Log every 5 iterations
  enable_tb_logging: true           # Keep metrics
  visualize_contact: false          # CRITICAL: No visualization (slow)
  visualize_every: 100
  visualize_output_dir: "phase4_visualizations"

  # ======================================================================
  # Advanced Options (Optimized for speed)
  # ======================================================================
  use_mesh_cache: true              # Cache meshes when possible
  cache_max_age: 5                  # Refresh cache every 5 iters
  contact_grad_clip: 5.0            # Prevent gradient explosion
  fallback_on_error: true           # Continue on errors
  use_pytorch3d: true               # Use fast distance computation

# ================================================================
# PHASE 5: Fix warmup_iters
# ================================================================
phase5:
  enabled: true
  phase5_start_iter: 100
  total_iterations: 1000

  # ================================================================
  # FIX 2: Change warmup_iters to 0
  # ================================================================
  warmup_iters: 0                 # ← CHANGE: from 50 to 0
  finetune_start_iter: 800

  # Temporal consistency settings
  temporal_window: 5
  w_velocity: 0.5
  w_acceleration: 0.1
  w_camera_motion: 0.3
  w_temporal: 1.0
  adaptive_weight: true

  # Diffusion prior
  guidance_scale: 4.0
  min_step: 0.02
  max_step: 0.98
  prediction_respacing: 100
  w_schedule: "dream"

  # Adaptive contact zones
  proximity_threshold: 0.015
  min_contact_verts: 5
  max_contact_verts: 50
  contact_update_freq: 10
  penalize_palm: true

  # Logging
  log_phase5_every: 10
  enable_geometry_sampling: false

# ========================================================================
# ULTRA-FAST TRAINING SETTINGS
# ========================================================================
training:
  num_epochs: 100
  max_steps: -1
  eval_every_epoch: 999  # Disable evaluation
  log_every: 1           # Log immediately
  gradient_clip: 0.5

# ========================================================================
# MINIMAL DATASET (single batch)
# ========================================================================
dataset:
  train:
    type: "train"
    batch_size: 1
    drop_last: false  # ← ADDED: Required by create_dataset
    shuffle: true
    num_workers: 0
    prefetch_factor: 2  # Optional but good

  valid:
    type: "val"  # ← Also add for consistency
    enabled: false
    batch_size: 1
    drop_last: false
    shuffle: false      # ← CRITICAL: Missing field causing error
    num_workers: 0
    pixel_per_batch: 256  # Reduced from 512

# ========================================================================
# MINIMAL MODEL (tiny architecture)
# ========================================================================
model:
  # Implicit network (SDF network)
  implicit_network:
    feature_vector_size: 32
    d_in: 3
    d_out: 1
    dims: [32, 32]
    init: geometry
    bias: 0.6
    skip_in: []
    weight_norm: true
    multires: 1
    cond: pose

  rendering_network:
    feature_vector_size: 32
    mode: pose
    d_in: 14
    d_out: 3
    dims: [32]
    weight_norm: true
    multires_view: -1

  bg_implicit_network:
    feature_vector_size: 32
    d_in: 4
    d_out: 1
    dims: [32, 32]
    init: none
    bias: 0.0
    skip_in: []
    weight_norm: false
    multires: 2
    cond: frame
    dim_frame_encoding: 8

  bg_rendering_network:
    feature_vector_size: 32
    mode: nerf_frame_encoding
    d_in: 3
    d_out: 3
    dims: [32]
    weight_norm: false
    multires_view: 1
    dim_frame_encoding: 8

  density:
    params_init:
      beta: 0.1
    beta_min: 0.0001

  ray_sampler:
    near: 0.0
    N_samples: 8          # Reduced for speed
    N_samples_eval: 8
    N_samples_extra: 4
    eps: 0.1
    beta_iters: 1
    max_total_iters: 1
    N_samples_inverse_sphere: 4
    add_tiny: 1.0e-06

  # SDF bounding sphere
  sdf_bounding_sphere: 1.0

# ========================================================================
# LOGGING (minimal output)
# ========================================================================
logging:
  log_images_every: 999999
  log_mesh_every: 999999
  log_to_file: true
  verbose: true  # Show checkpoint loading details

# ========================================================================
# VALIDATION DISABLED (critical for speed)
# ========================================================================
validation:
  enabled: false

# Optimizer (not critical for single step)
optimizer:
  lr: 0.0001
  type: "adam"
  weight_decay: 0.0
# Quick test overrides
experiment:
  name: 'ghop_quick_bottle_1'
  description: 'Quick test for Bottle_1'

# ================================================================
# LOSS WEIGHTS (ADDED FOR VERIFICATION)
# ================================================================
loss:
  w_rgb: 10.0
  w_mask: 5.0
  w_mano_cano: 0.5
  w_eikonal: 0.1
  w_smooth: 0.01
  w_semantic: 1.0
  w_opacity_sparse: 0.1
