# Save as: confs/ghop_stage3_full_pipeline.yaml

# ================================================================
# STAGE 3: Full Pipeline Training
# Phases: 3 (GHOP SDS) + 4 (Contact) + 5 (Temporal)
# Must match Stage 2 network architecture EXACTLY
# ================================================================

# Dataset Configuration (same as Stage 2)
dataset:
  train:
    batch_size: 1
    drop_last: false
    num_workers: 4
    prefetch_factor: 2
    shuffle: true
    type: train
  valid:
    batch_size: 1
    enabled: false
    type: val
experiment:
  description: Full pipeline with Phase 3+4+5
  name: ghop_stage3_full_pipeline
logging:
  log_images_every: 50
  log_mesh_every: 500
  log_to_file: true
  verbose: true
loss:
  rgb_loss_type: l1
  w_contact: 10.0
  w_eikonal: 1.0
  w_mask: 0.1
  w_rgb: 1.0
  w_smooth: 0.005
  w_temporal: 1.0
model:
  bg_implicit_network:
    bias: 0.0
    cond: frame
    d_in: 4
    d_out: 1
    dim_frame_encoding: 32
    dims:
    - 256
    - 256
    - 256
    feature_vector_size: 256
    init: none
    multires: 10
    skip_in: []
    weight_norm: true
  bg_rendering_network:
    d_in: 259
    d_out: 3
    dim_frame_encoding: 32
    dims:
    - 128
    feature_vector_size: 256
    mode: nerf_frame_encoding
    multires_view: 4
    weight_norm: true
  density:
    beta_min: 0.0001
    params_init:
      beta: 0.1
  implicit_network:
    bias: 0.6
    cond: pose
    d_in: 3
    d_out: 1
    dims:
    - 256
    - 256
    - 256
    - 256
    feature_vector_size: 256
    init: geometry
    multires: 6
    skip_in:
    - 4
    weight_norm: true
  ray_sampler:
    N_samples: 64
    N_samples_eval: 128
    N_samples_extra: 32
    N_samples_inverse_sphere: 32
    beta_iters: 10
    eps: 0.1
    max_total_iters: 5
    near: 0.0
  rendering_network:
    d_implicit_features: 256
    d_in: 270
    d_out: 3
    dims:
    - 256
    - 256
    - 256
    - 256
    - 256
    - 256
    - 256
    - 256
    feature_vector_size: 256
    mode: pose
    multires_view: 0
    time_code_dim: 32
    weight_norm: true
  sdf_bounding_sphere: 1.5
optimizer:
  lr: 3.0e-05
  type: adam
  weight_decay: 0.0
phase3:
  enabled: true
  ghop:
    config_path: checkpoints/ghop/config.yaml
    device: cuda
    text_lib: null
    unet_checkpoint: checkpoints/ghop/last.ckpt
    unet_use_pretrained: false
    unified_checkpoint: checkpoints/ghop/last.ckpt
    vqvae_checkpoint: checkpoints/ghop/last.ckpt
    vqvae_use_pretrained: true
  grid_resolution: 24
  phase3_end_iter: 99999
  phase3_start_iter: 0
  sds:
    diffusion_steps: 1000
    guidance_scale: 3.0
    max_step_ratio: 0.98
    min_step_ratio: 0.02
    noise_schedule: linear
    prediction_respacing: 50
  sds_iters: 1
  spatial_lim: 1.5
  use_modular_init: true
  w_sds: 10.0
  warmup_iters: 0
phase4:
  cache_max_age: 10
  contact_duration: 99999
  contact_grad_clip: 5.0
  contact_refinement:
    collision_thresh: 0.005
    contact_thresh: 0.01
    contact_zones: zones
    enabled: true
    w_attraction: 1.0
    w_damping: 0.1
    w_penetration: 5.0
  contact_start_iter: 100
  contact_warmup_iters: 500
  enable_tb_logging: true
  enabled: true
  fallback_on_error: true
  log_contact_every: 10
  mesh_extraction:
    enabled: true
    extract_every: 5
    resolution: 64
    threshold: 0.0
  use_mesh_cache: true
  use_pytorch3d: true
  visualize_contact: false
  visualize_every: 100
  visualize_output_dir: phase4_visualizations
  w_contact: 1.0
phase5:
  adaptive_weight: true
  contact_update_freq: 10
  enable_geometry_sampling: false
  enabled: true
  guidance_scale: 3.0
  log_phase5_every: 10
  max_contact_verts: 50
  max_step: 0.98
  min_contact_verts: 5
  min_step: 0.02
  penalize_palm: true
  phase5_start_iter: 5000
  prediction_respacing: 100
  proximity_threshold: 0.015
  temporal_window: 3
  total_iterations: 99999
  use_scheduler: false
  w_acceleration: 0.001
  w_camera_motion: 0.005
  w_schedule: dream
  w_temporal: 0.01
  w_velocity: 0.005
  warmup_iters: 500
training:
  eval_every_epoch: 999
  gradient_clip: 1.0
  log_every: 10
  max_steps: -1
  num_epochs: 20
validation:
  enabled: false
