# Priority 1 Tuning - Run A: Conservative reduction
# Temporal weight: 0.05 (50% reduction from 0.1 baseline)
# RGB weight: 1.0 (standard)

phase3:
  enabled: true
  w_sds: 50.0  # ✅ Match validated baseline (NOT 100.0)
  ghop:
    config_path: checkpoints/ghop/config.yaml
    device: cuda
    unified_checkpoint: checkpoints/ghop/last.ckpt
    vqvae_checkpoint: checkpoints/ghop/last.ckpt
    vqvae_use_pretrained: true
    unet_checkpoint: checkpoints/ghop/last.ckpt
    unet_use_pretrained: true
  sds:
    diffusion_steps: 1000
    guidance_scale: 4.0
    prediction_respacing: 50
    min_step_ratio: 0.02
    max_step_ratio: 0.98
    noise_schedule: linear
  phase3_start_iter: 0
  phase3_end_iter: 99999
  warmup_iters: 0

phase4:
  enabled: false

phase5:
  enabled: false

training:
  num_epochs: 20  # ✅ Match validated Stage 2 duration
  max_steps: -1
  eval_every_epoch: 999
  log_every: 10
  gradient_clip: 1.0

loss:
  w_rgb: 1.5          # Boost RGB priority
  w_temporal: 0.03    # 70% reduction (testing aggressive sharpening)
  w_mask: 0.1
  w_eikonal: 1.0
  w_smooth: 0.005
  rgb_loss_type: "l1"

# Dataset (same as current config)
dataset:
  train:
    type: "train"
    batch_size: 1
    drop_last: false
    shuffle: true
    num_workers: 4
    prefetch_factor: 2
  valid:
    type: "val"
    enabled: false
    batch_size: 1

# Model architecture (MUST match Stage 1 - copy from current config)
model:
  implicit_network:
    feature_vector_size: 256
    d_in: 3
    d_out: 1
    dims: [256, 256, 256, 256]
    init: geometry
    bias: 0.6
    skip_in: [4]
    weight_norm: true
    multires: 6
    cond: pose

  rendering_network:
    feature_vector_size: 256
    mode: pose
    d_in: 270
    d_out: 3
    dims: [256, 256, 256, 256, 256, 256, 256, 256]
    weight_norm: true
    multires_view: 0
    time_code_dim: 32
    d_implicit_features: 256

  bg_implicit_network:
    feature_vector_size: 256
    d_in: 4
    d_out: 1
    dims: [256, 256, 256]
    init: none
    bias: 0.0
    skip_in: []
    weight_norm: true
    multires: 10
    cond: frame
    dim_frame_encoding: 32

  bg_rendering_network:
    feature_vector_size: 256
    mode: nerf_frame_encoding
    d_in: 259
    d_out: 3
    dims: [128]
    weight_norm: true
    multires_view: 4
    dim_frame_encoding: 32

  density:
    params_init:
      beta: 0.1
    beta_min: 0.0001

  ray_sampler:
    near: 0.0
    N_samples: 64
    N_samples_eval: 128
    N_samples_extra: 32
    eps: 0.1
    beta_iters: 10
    max_total_iters: 5
    N_samples_inverse_sphere: 32

  sdf_bounding_sphere: 1.5

optimizer:
  lr: 0.00005
  type: "adam"
  weight_decay: 0.0

experiment:
  name: 'stage2_tuned_runB'