# ================================================================
# Stage 3: 1-EPOCH QUICK TEST
# Testing SDS integration with minimal training time
# ================================================================

# ================================================================
# PHASE 3: SDS GUIDANCE (1 EPOCH)
# ================================================================
phase3:
  enabled: true

  # GHOP Checkpoints - SAME AS BEFORE
  ghop:
    config_path: checkpoints/ghop/config.yaml
    device: cuda
    unet_checkpoint: /home/fredcui/Projects/ghop/output/joint_3dprior/mix_data/checkpoints/last.ckpt
    unified_checkpoint: /home/fredcui/Projects/ghop/output/joint_3dprior/mix_data/checkpoints/last.ckpt
    vqvae_checkpoint: /home/fredcui/Projects/ghop/output/joint_3dprior/mix_data/checkpoints/last.ckpt
    unet_use_pretrained: true
    vqvae_use_pretrained: true
    # ✅ NEW: Use Hugging Face CLIP instead of checkpoint CLIP
    use_huggingface_clip: true
    clip_model_name: "openai/clip-vit-large-patch14"  # Optional: default if not specified

  grid_resolution: 64
  spatial_lim: 1.5

  # Phase 3 Boundaries - SDS active with scheduled weights
  # Mesh extraction happens at step ~1500, so SDS weight → 0.05 by step 1400
  phase3_start_iter: 0
  phase3_end_iter: 1499        # SDS weight scheduled to 0.0 at step 1500

  # SDS Configuration - SAME
  sds:
    diffusion_steps: 1000
    guidance_scale: 3.0
    max_step_ratio: 0.98
    min_step_ratio: 0.02
    noise_schedule: linear
    prediction_respacing: 50

  sds_iters: 1
  use_modular_init: true

  # ================================================================
  # CRITICAL FIX: Scheduled SDS weights (replaces w_sds: 10.0)
  # ================================================================
  # OLD: w_sds: 10.0  (caused 99.5% loss dominance, 500:1 gradient ratio)
  # NEW: Scheduled weights to balance RGB and SDS throughout training
  w_sds_schedule:
    enabled: true

    # Keyframe schedule (linear interpolation between points)
    step_0: 0.5        # Start balanced (vs 10.0 previously)
    step_250: 0.5      # Stable warmup
    step_500: 0.3      # Begin reduction
    step_750: 0.25     # Continue reduction
    step_1000: 0.2     # Mid-training
    step_1200: 0.1     # Approaching extraction
    step_1400: 0.05    # Final refinement
    step_1500: 0.0     # Phase 4 starts (SDS OFF)

    interpolation: "linear"

  # Diagnostic monitoring for scheduled weights
  diagnostics:
    rgb_convergence_check:
      enabled: true
      step: 1000
      threshold: 0.08    # Expect RGB < 0.08 at halfway point
      warning_only: true

    sds_trend_check:
      enabled: true
      check_every: 200
      window: 400
      max_increase: 0.2  # Warn if SDS increases > 20%

    log_sds_weight_every: 50  # Log current weight frequently

  warmup_iters: 0

# ================================================================
# PHASE 4: CONTACT REFINEMENT (1 EPOCH)
# ================================================================
phase4:
  enabled: true

  # Phase boundaries - SCALED DOWN (30 epochs → 1 epoch)
  # Original: 20000 (epoch 10) → New: 1000 (epoch 0.5)
  contact_start_iter: 1500      # CHANGED: Start halfway through epoch 1
  contact_end_iter: 1949
  contact_warmup_iters: 10     # CHANGED: Reduced from 500

  # Thresholds - SAME
  contact_thresh: 0.20
  collision_thresh: 0.08

  # Contact weights - SAME
  w_contact: 1.0
  w_penetration: 100.0
  w_attraction: 10.0
  w_damping: 0.0

  mesh_resolution: 128
  mesh_padding: 0.1

  log_contact_every: 50

# ================================================================
# PHASE 5: TEMPORAL CONSISTENCY (1 EPOCH)
# ================================================================
phase5:
  enabled: true

  phase5_start_iter: 1950       # CHANGED: Start at step 1100 (epoch 0.55)
  phase5_end_iter: 2000        # Explicit termination at training end

  # Scheduler - SCALED DOWN
  use_scheduler: true
  scheduler:
    total_iterations: 2000      # CHANGED: 1 epoch ≈ 2000 steps
    warmup_iters: 0
    phase3_start: 0
    phase4_start: 1500          # CHANGED: Scaled from 20000
    phase5_start: 1950          # CHANGED: Scaled from 20500
    finetune_start: 1980        # CHANGED: Last 10% of epoch (scaled from 50000)

  # Temporal weights - SAME
  w_temporal: 0.01
  w_velocity: 0.005
  w_acceleration: 0.005
  w_camera_motion: 0.001

  # Adaptive contacts - SAME
  adaptive_contacts:
    enabled: false              # Disabled to save ~125 MB
    k_neighbors: 5
    contact_threshold: 0.10
    update_frequency: 50
    cache_size: 50

  temporal:
    history_size: 3             # Reduced from 10 to minimum (saves 70% memory)
    velocity_weight: 1.0
    acceleration_weight: 0.5

  log_phase5_every: 100

# ================================================================
# SCENE & MODEL (UNCHANGED)
# ================================================================
scene_bounding_sphere: 6.0

model:
  density:
    params_init:
      beta: 0.1
    beta_min: 0.0001

  ray_sampler:
    near: 0.0
    N_samples: 64
    N_samples_eval: 128
    N_samples_extra: 32
    eps: 0.1
    beta_iters: 10
    max_total_iters: 5
    N_samples_inverse_sphere: 32
    add_tiny: 0.000001

  implicit_network:
    feature_vector_size: 256
    d_in: 3
    d_out: 1
    dims: [256, 256, 256, 256, 256, 256, 256, 256]
    init: geometry
    bias: 0.6
    skip_in: [4]
    weight_norm: true
    multires: 6
    cond: pose

  rendering_network:
    feature_vector_size: 256
    mode: pose
    d_in: 270
    d_out: 3
    dims: [256, 256, 256, 256]
    weight_norm: true
    multires_view: 0
    d_implicit_features: 256

  bg_implicit_network:
    feature_vector_size: 256
    d_in: 4
    d_out: 1
    dims: [256, 256, 256, 256, 256, 256, 256, 256]
    init: none
    bias: 0.0
    skip_in: [4]
    weight_norm: false
    multires: 10
    cond: frame
    dim_frame_encoding: 32

  bg_rendering_network:
    feature_vector_size: 256
    mode: nerf_frame_encoding
    d_in: 259
    d_out: 3
    dims: [128]
    weight_norm: false
    multires_view: 4
    dim_frame_encoding: 32
    multires_xyz: 42
    d_implicit_features: 171

# ================================================================
# DATASET (UNCHANGED)
# ================================================================
dataset:
  dataset_path: data/hold_MC1_ho3d/build
  seq_name: hold_MC1_ho3d

  train:
    type: train
    batch_size: 1
    drop_last: false
    shuffle: true
    num_workers: 4

  valid:
    type: val
    batch_size: 1
    drop_last: false
    shuffle: false
    pixel_per_batch: 512
    enabled: false

# ================================================================
# LOSS (UNCHANGED)
# ================================================================
loss:
  w_rgb: 1.0
  w_mask: 0.3              # CHANGED: from 0.1
  w_mask_edge: 0.1         # NEW: Add this line
  w_eikonal: 1.0
  w_smooth: 0.005
  w_temporal: 1.0
  rgb_loss_type: "l1"

# ================================================================
# TRAINING - 1 EPOCH ONLY
# ================================================================
training:
  num_epochs: 1                 # CHANGED: 30 → 1
  max_steps: 2000               # CHANGED: 60000 → 2000 (1 epoch)
  eval_every_epoch: 999           # CHANGED: Evaluate after the single epoch
  log_every: 20                 # CHANGED: More frequent logging (every 20 steps)
  gradient_clip: 1.0

# ================================================================
# OPTIMIZER (UNCHANGED)
# ================================================================
optimizer:
  lr: 0.0001
  type: "adam"
  weight_decay: 0.0
  betas: [0.9, 0.999]
  eps: 1.0e-08

# Learning rate scheduler - cosine annealing
scheduler:
  type: "cosine"
  T_max: 2000                  # Full 30 epochs
  eta_min: 0.00001              # 10× reduction
  warmup_steps: 200            # 1 epoch warmup

# ================================================================
# EXPERIMENT - NEW NAME FOR TEST
# ================================================================
experiment:
  name: 'stage3_1epoch_test_sds_fix'  # CHANGED: Descriptive test name

# ================================================================
# CHECKPOINT - SAME STARTING POINT
# ================================================================
checkpoint:
  resume_from: 'outputs/stage2_official_cb20a1702_FIXED/checkpoints/last.ckpt'
  load_optimizer: false
  load_scheduler: false
# ================================================================
# CALLBACKS - DUAL CHECKPOINT SYSTEM FOR 1-EPOCH TEST
# ================================================================
callbacks:
  # Epoch-based checkpoint (saves at end of epoch)
  checkpoint:
    monitor: "train_loss"                # Don't wait for metrics
    mode: "min"
    save_top_k: 1                # Keep only 1 best (saves space)
    every_n_epochs: 1            # Save after 1 epoch completes
    save_last: true              # Always save last.ckpt
    dirpath: "checkpoints"
    filename: "epoch{epoch:02d}-loss{loss:.4f}"

  # Step-based checkpoint (saves every 500 steps for 1-epoch test)
  checkpoint_steps:
    monitor: null                # Unconditional save
    mode: "min"
    save_top_k: -1               # Save all step checkpoints
    every_n_train_steps: 500     # Save at steps 500, 1000, 1500, 2000
    save_last: false             # Don't duplicate last.ckpt
    filename: "step{step:05d}"
    save_on_train_epoch_end: false
    verbose: true