# File: confs/test_checkpoint_loading.yaml
# Update checkpoint path to use ../checkpoints (relative to code/)

defaults:
  - sanity_check_fast

phase3:
  enabled: true
  use_modular_init: true

  ghop:
    unified_checkpoint: "checkpoints/ghop/last.ckpt"
    vqvae_checkpoint: "checkpoints/ghop/last.ckpt"
    unet_checkpoint: "checkpoints/ghop/last.ckpt"
    config_path: "checkpoints/ghop/config.yaml"
    vqvae_use_pretrained: true
    unet_use_pretrained: true
    device: "cuda"
    text_lib: null

  warmup_iters: 0
  w_sds: 5000.0
  sds_iters: 1
  grid_resolution: 32
  spatial_lim: 1.5

  sds:
    diffusion_steps: 1000
    prediction_respacing: 10
    noise_schedule: "linear"
    min_step_ratio: 0.02
    max_step_ratio: 0.98
    guidance_scale: 4.0

phase4:
  enabled: true                              # ← SET THIS TO TRUE

  # Contact refinement parameters
  contact_thresh: 0.01                       # 10mm contact zone radius
  collision_thresh: 0.005                    # 5mm penetration threshold
  contact_start_iter: 500                    # Start after SDS stage completes
  w_contact: 10.0                            # Contact loss weight
  mesh_resolution: 128                       # Marching cubes resolution (128³)
  contact_warmup_iters: 100                  # Warmup from 0 to w_contact over 100 iters

  # Logging
  log_contact_every: 50                      # Log contact metrics every 50 steps

phase5:
  enabled: false

# ========================================================================
# ULTRA-FAST TRAINING SETTINGS
# ========================================================================
training:
  num_epochs: 1          # Single epoch only
  max_steps: 1           # Single training step
  eval_every_epoch: 999  # Disable evaluation
  log_every: 1           # Log immediately
  gradient_clip: 0.5

# ========================================================================
# MINIMAL DATASET (single batch)
# ========================================================================
dataset:
  train:
    type: "train"
    batch_size: 2
    drop_last: false  # ← ADDED: Required by create_dataset
    shuffle: false
    num_workers: 0
    prefetch_factor: 2  # Optional but good

  valid:
    type: "val"  # ← Also add for consistency
    enabled: false
    batch_size: 1
    drop_last: false
    shuffle: false      # ← CRITICAL: Missing field causing error
    num_workers: 0
    pixel_per_batch: 512

# ========================================================================
# MINIMAL MODEL (tiny architecture)
# ========================================================================
model:
  # Implicit network (SDF network)
  implicit_network:
    feature_vector_size: 32
    d_in: 3
    d_out: 1
    dims: [32, 32]
    init: geometry          # ← Was missing (was geometric_init)
    bias: 0.6
    skip_in: []
    weight_norm: true
    multires: 1
    cond: pose              # ← CRITICAL: Was missing!

  rendering_network:
    feature_vector_size: 32
    mode: pose
    d_in: 14
    d_out: 3
    dims: [32]
    weight_norm: true
    multires_view: -1       # ← Was multires: 0 (use correct field name)

  bg_implicit_network:      # ← Was missing entire section
    feature_vector_size: 32
    d_in: 4
    d_out: 1
    dims: [32, 32]
    init: none
    bias: 0.0
    skip_in: []
    weight_norm: false
    multires: 2
    cond: frame
    dim_frame_encoding: 8

  bg_rendering_network:
    feature_vector_size: 32
    mode: nerf_frame_encoding
    d_in: 3
    d_out: 3
    dims: [32]
    weight_norm: false
    multires_view: 1
    dim_frame_encoding: 8

  density:                  # ← Was missing entire section
    params_init:
      beta: 0.1
    beta_min: 0.0001

  ray_sampler:
    near: 0.0
    N_samples: 8
    N_samples_eval: 8
    N_samples_extra: 4
    eps: 0.1
    beta_iters: 1
    max_total_iters: 1
    N_samples_inverse_sphere: 4
    add_tiny: 1.0e-06

  # SDF bounding sphere
  sdf_bounding_sphere: 1.0

# ========================================================================
# LOGGING (minimal output)
# ========================================================================
logging:
  log_images_every: 999999
  log_mesh_every: 999999
  log_to_file: true
  verbose: true  # Show checkpoint loading details

# ========================================================================
# VALIDATION DISABLED (critical for speed)
# ========================================================================
validation:
  enabled: false

# Optimizer (not critical for single step)
optimizer:
  lr: 1.0e-4